<div style="margin:20px;">
<table id="jogadores"  class="table table-striped table-bordered" style="width:100%" >
    <thead>
        <tr>
            <th style='text-align: center'>ID</th>
            <th style='text-align: left'>Nome</th>
            <th style='text-align: center'>Pontos</th>
            <th >Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->jogadores as $jogador) {?>
            
            <tr>
                <td style='text-align: center'><?php echo $jogador['id']; ?></td>
                <td><?php echo $jogador['nome']; ?></td>
                <td style='text-align: center'><?php echo $jogador['pontuacao']; ?></td>
                <td><a href="/jogador/atualizar/id/<?php echo $jogador['id'] ?>" class="btn btn-primary btn-sm">Editar</a>
                   <a href="/jogador/excluir/id/<?php echo $jogador['id'] ?>" class="btn btn-danger btn-sm">Excluir</a></td>
            </tr>
        <?php } ?>

    </tbody>
</table>
</div>
<script>
$(document).ready(function() {  
    $.noConflict(); 
    $('#jogadores').DataTable({
        "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
            },
        //"paging": false,
        "order": [ 0, 'desc' ]
    }); 
});
</script>