<div style="margin:20px;">
<table id="etapas"  class="table table-striped table-bordered" style="width:100%" >
    <thead>
        <tr>
            <th style='text-align: center'>ID</th>
            <th style='text-align: center'>mês</th>
            <th style='text-align: center'>Ano</th>
            <th style='text-align: center'>Total Duplas</th>
            <th >Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->etapas as $etapa) {?>
            
            <tr>
                <td style='text-align: center'><?php echo $etapa['id']; ?></td>
                <td style='text-align: center'><?php echo $etapa['mes']; ?></td>
                <td style='text-align: center'><?php echo $etapa['ano']; ?></td>
                <td style='text-align: center'><?php echo $etapa['duplas']; ?></td>
                <td><a href="/etapa/atualizar/id/<?php echo $etapa['id'] ?>" class="btn btn-primary btn-sm">Editar</a>
                   <a href="/etapa/excluir/id/<?php echo $etapa['id'] ?>" class="btn btn-danger btn-sm">Excluir</a></td>
            </tr>
        <?php } ?>

    </tbody>
</table>
</div>
<script>
$(document).ready(function() {  
    $.noConflict(); 
    $('#etapas').DataTable({
        "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
            },
        //"paging": false,
        "order": [ 0, 'desc' ]
    }); 
});
</script>