<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link href="/bootstrap-4.3.1/dist/css/bootstrap.css" rel="stylesheet">
      <link href="/bootstrap-4.3.1/dist/css/bootstrap-reboot.css" rel="stylesheet">
      <link href="css/bootstrap-responsive.min.css" rel="stylesheet">

      <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
      <script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
      <script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>    

      <title>Torneio de Canastra</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Alterna navegação" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
        <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Jogadores</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/jogador/add">Cadastrar</a>
              <a class="dropdown-item" href="/jogador/listagem">Listar</a>
            </div>
          </li>
          <li class="nav-item dropdown"> <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Etapas</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/etapa/add">Cadastrar</a>
              <a class="dropdown-item" href="/etapa/listagem">Listar</a>
              <a class="dropdown-item" href="#">Não clicar</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>  


    <div class="span6" style="border: 1px solid green"> 
    <?php echo $this->layout()->content; ?>
    </div>

    <script src="/js/jquery-3.4.1.js" ></script>
    <script src="/bootstrap-4.3.1/dist/js/bootstrap.js"></script>
    <script src="/bootstrap-4.3.1/site/docs/4.3/assets/js/vendor/anchor.min.js"></script>
    <script src="/bootstrap-4.3.1/site/docs/4.3/assets/js/vendor/clipboard.min.js"></script>
    <script src="/bootstrap-4.3.1/site/docs/4.3/assets/js/src/application.js"></script>
    <script src="/bootstrap-4.3.1/site/docs/4.3/assets/js/src/search.js"></script>
    <script src="/bootstrap-4.3.1/site/docs/4.3/assets/js/src/ie-emulation-modes-warning.js"></script>

  </body>
</html>




