CREATE TABLE dupla (id SERIAL, id_etapa INT NOT NULL, id_jogador1 INT NOT NULL, id_jogador2 INT NOT NULL, PRIMARY KEY(id));
CREATE TABLE etapa (id SERIAL, mes INT NOT NULL, ano INT NOT NULL, PRIMARY KEY(id));
CREATE TABLE jogador (id SERIAL, nome VARCHAR(150) NOT NULL, pontuacao INT NOT NULL, PRIMARY KEY(id));
ALTER TABLE dupla ADD CONSTRAINT dupla_id_dupla_etapa_id FOREIGN KEY (id_dupla) REFERENCES etapa(id) NOT DEFERRABLE INITIALLY IMMEDIATE;
